
server:
  port: 9500

spring:
  application:
    name: api-gateway2
  cloud:
    gateway:
      routes:
        - id: api-gateway2
          #lb:lb代表从注册中心获取服务，后面接需要转发到的服务名称，这个服务名称必须跟eureka中的对应
          uri: lb://provider
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer02:9001/eureka/,http://eurekaServer01:9000/eureka/

