server:
  port: 9300

spring:
  application:
    name: feign_consumer02

eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer02:9001/eureka/,http://eurekaServer01:9000/eureka/

feign:
  hystrix:
    enabled: true
