server:
  port: 9300

spring:
  application:
    name: feign_consumer02


eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer02:9001/eureka/,http://eurekaServer01:9000/eureka/

feign:
  hystrix:
    enabled: true

#feign自定义负载均衡
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试