
server:
  port: 9400

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer02:9001/eureka/,http://eurekaServer01:9000/eureka/


zuul:
  routes:
    api-zhangwx:
      path: /api/**
      serviceId: feign_consumer02
