spring:
  application:
    name: eureka02

server:
  port: 9001

eureka:
  instance:
    #\u8BBE\u7F6Eeureka\u5B9E\u4F8B\u540D\u79F0\uFF0C\u5EFA\u8BAE\u4E0E\u914D\u7F6E\u6587\u4EF6\u7684\u53D8\u91CF\u76F8\u540C\uFF0C\u5FC5\u987B\u548CLinux\u7CFB\u7EDF\u57DF\u540D\u76F8\u540C
    hostname: eurekaserver02
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      # \u8BBE\u7F6E\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740\uFF0C\u6307\u5411\u53E6\u4E00\u4E2A\u6CE8\u518C\u4E2D\u5FC3\uFF0C\u4F7F\u7528\u57DF\u540D\u4F5C\u4E3A\u8BBF\u95EE\u8DEF\u5F84
      defaultZone: http://eurekaServer01:9000/eureka/
  server:
    enable-self-preservation: false




