spring:
  application:
    name: eureka02

server:
  port: 9001

eureka:
  instance:
    hostname: eurekaserver02
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://eurekaServer01:9000/eureka/
  server:
    enable-self-preservation: false




